version: '3.4'

services:
  dnp_provisioning:
    build: ./build
    image: dnp_provisioning
    container_name: dnp_provisioning_dev
    volumes:
      - ./sample_files/VPN.mobileconfig:/usr/share/nginx/html/VPN.mobileconfig
      # admin/admin
      - ./sample_files/htpasswd:/etc/nginx/htpasswd
    ports:
      - 8080:80